// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "url": "https://github.com/httplock/httplock"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ca": {
            "get": {
                "description": "returns the public CA in PEM format",
                "produces": [
                    "application/text"
                ],
                "summary": "Get CA",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/": {
            "get": {
                "description": "Lists the roots",
                "produces": [
                    "application/json"
                ],
                "summary": "Root List",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/diff": {
            "get": {
                "description": "Returns the differences between two roots",
                "produces": [
                    "application/json"
                ],
                "summary": "Root Diff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "root 1 hash or uuid",
                        "name": "root",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "root 2 hash or uuid",
                        "name": "root2",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/dir": {
            "get": {
                "description": "Lists a directory in a root",
                "produces": [
                    "application/json"
                ],
                "summary": "Root Dir",
                "parameters": [
                    {
                        "type": "string",
                        "description": "root hash or uuid",
                        "name": "root",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "path to list",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/export": {
            "get": {
                "description": "Exports a hash, returning a tar+gz",
                "produces": [
                    "application/x-gtar"
                ],
                "summary": "Root export",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hash",
                        "name": "root",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/file": {
            "get": {
                "description": "Get file contents in a root",
                "produces": [
                    "application/octet-stream"
                ],
                "summary": "Root File",
                "parameters": [
                    {
                        "type": "string",
                        "description": "root hash or uuid",
                        "name": "root",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "path of file",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "content-type to set on the returned file",
                        "name": "ct",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/import": {
            "put": {
                "description": "Imports a root hash from a tar+gz",
                "consumes": [
                    "application/x-gtar"
                ],
                "summary": "Root import",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hash",
                        "name": "root",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/info": {
            "get": {
                "description": "Get info about a specific path entry in a root",
                "produces": [
                    "application/json"
                ],
                "summary": "Root Info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "root hash or uuid",
                        "name": "root",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "path of file",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/root/{root}/resp": {
            "get": {
                "description": "Return the response from a request, including headers",
                "summary": "Root Response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "root hash or uuid",
                        "name": "root",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": "path of request",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "request hash",
                        "name": "hash",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/token": {
            "post": {
                "description": "returns a new uuid for recording a session",
                "produces": [
                    "application/json"
                ],
                "summary": "Token create",
                "parameters": [
                    {
                        "type": "string",
                        "description": "hash used to initialize the response cache",
                        "name": "hash",
                        "in": "query"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/token/{id}": {
            "delete": {
                "description": "returns a new uuid for recording a session",
                "produces": [
                    "application/json"
                ],
                "summary": "Token delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/api/token/{id}/save": {
            "post": {
                "description": "Saves a uuid token, returning an immutable hash",
                "produces": [
                    "application/json"
                ],
                "summary": "Token save",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "httplock API",
	Description:      "HTTP reproducible proxy server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
