name: Docker

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 06 * * *'

jobs:

  docker:
    name: Docker
    runs-on: ubuntu-latest
    permissions:
      # id-token is used by cosign's OIDC based signing
      # https://blog.chainguard.dev/zero-friction-keyless-signing-with-github-actions/
      # TODO: make token conditional: "${{ github.event_name != 'pull_request' && github.repository_owner == 'httplock' && 'write' || 'none' }}"
      id-token: 'write'

    strategy:
      matrix:
        type: ["scratch", "alpine"]

    steps:
    - name: Prepare
      id: prep
      run: |
        EXT=""
        if [ "${{ matrix.type }}" != "scratch" ]; then
          EXT="-${{ matrix.type }}"
        fi
        HUB_IMAGE=httplock/httplock
        GHCR_IMAGE=ghcr.io/httplock/httplock
        VERSION=noop
        if [ "${{ github.event_name }}" = "schedule" ]; then
          VERSION=edge
        elif [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="${GITHUB_REF#refs/tags/}"
        elif [[ $GITHUB_REF == refs/heads/* ]]; then
          VERSION="${GITHUB_REF#refs/heads/}"
          if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
            VERSION=edge
          fi
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          VERSION="pr-${{ github.event.number }}"
        fi
        VERSION="$(echo "${VERSION}" | sed -r 's#/+#-#g')"
        TAGS="${HUB_IMAGE}:${VERSION}${EXT},${GHCR_IMAGE}:${VERSION}${EXT}"
        if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
          MINOR="${VERSION%.*}"
          MAJOR="${MINOR%.*}"
          TAGS="${TAGS},${HUB_IMAGE}:${MINOR}${EXT},${HUB_IMAGE}:${MAJOR}${EXT}"
          TAGS="${TAGS},${GHCR_IMAGE}:${MINOR}${EXT},${GHCR_IMAGE}:${MAJOR}${EXT}"
          if [ "${{ matrix.type }}" == "scratch" ]; then
            TAGS="${TAGS},${HUB_IMAGE}:latest"
            TAGS="${TAGS},${GHCR_IMAGE}:latest"
          else
            TAGS="${TAGS},${HUB_IMAGE}:${{ matrix.type }}"
            TAGS="${TAGS},${GHCR_IMAGE}:${{ matrix.type }}"
          fi
        fi
        echo "::set-output name=version::${VERSION}"
        echo "::set-output name=cache::${GHCR_IMAGE}:buildcache${EXT}"
        echo "::set-output name=image_hub::${HUB_IMAGE}"
        echo "::set-output name=image_ghcr::${GHCR_IMAGE}"
        echo "::set-output name=tags::${TAGS}"
        echo "::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Check out code
      uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install cosign
      uses: sigstore/cosign-installer@main
     
    - name: Login to DockerHub
      if: github.repository_owner == 'httplock'
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      if: github.repository_owner == 'httplock'
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      id: build
      with:
        context: .
        file: ./Dockerfile.buildkit
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name != 'pull_request' && github.repository_owner == 'httplock' }}
        target: release-${{ matrix.type }}
        tags: ${{ steps.prep.outputs.tags }}
        cache-from: type=registry,ref=${{ steps.prep.outputs.cache }}
        cache-to: ${{ github.repository_owner == 'httplock' && format('type=registry,ref={0},mode=max', steps.prep.outputs.cache) || 'type=inline'}}
        labels: |
          org.opencontainers.image.created=${{ steps.prep.outputs.created }}
          org.opencontainers.image.source=${{ github.repositoryUrl }}
          org.opencontainers.image.version=${{ steps.prep.outputs.version }}
          org.opencontainers.image.revision=${{ github.sha }}
